apiVersion: v1
kind: ConfigMap
metadata:
  name: vets-service
  labels:
    app.kubernetes.io/name: vets-service
    app.kubernetes.io/part-of: petclinic
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: service
data:
  SPRING_PROFILES_ACTIVE: "docker,mysql"
  CONFIG_SERVER_URL: "http://config-server:8888"
  SPRING_DATASOURCE_URL: "jdbc:mysql://<rds-endpoint>:3306/petclinic"
