name: Docker Build Push

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string

      service-path:
        required: true
        type: string

      aws-region:
        required: true
        type: string

      aws-role:
        required: true
        type: string

      ecr-registry:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      image-tag: ${{ steps.vars.outputs.image_tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.aws-role }}
          aws-region: ${{ inputs.aws-region }}

      - name: Configure QEMU
        uses: docker/setup-qemu-action@v3

      - name: Configure Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set variables
        id: vars
        run: |
          echo "image_tag=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build ARM64 image
        run: |
          docker buildx build \
            --platform linux/arm64 \
            --load \
            -t ${{ inputs.ecr-registry }}/${{ inputs.service-name }}:${GITHUB_SHA::7} \
            ./${{ inputs.service-path }}

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ inputs.ecr-registry }}/${{ inputs.service-name }}:${GITHUB_SHA::7}
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: CRITICAL

      - name: Push image to ECR
        run: |
          docker push \
            ${{ inputs.ecr-registry }}/${{ inputs.service-name }}:${GITHUB_SHA::7}
